"""``planned_commands`` table — outbound *arr command queue (Phase 9).

Phase 9's command dispatcher writes a row here when it decides to issue a
search/refresh/etc command at a connector. The row carries the request payload,
the connector identity, and a status that walks ``pending → dispatched →
resolved`` (or ``failed`` on terminal error). ``arr_command_id`` is populated
once the *arr-side queues the command and returns its identifier — the
dispatcher polls that id to learn when the command finishes.

A surrogate UUIDv7 PK is used (rather than a composite key) because the row
is referenced by ``arr_command_id`` from the *arr side and the dispatcher's
poll path is best served by a single small key.

Partial index — keeps the polling hot path scoped to actionable rows:

    CREATE INDEX ix_planned_commands_pending
        ON planned_commands (connector_id, status, created_at)
        WHERE status = 'pending';

Wave 2 hand-patches the autogenerated migration to preserve the
``postgresql_where`` clause (autogenerate drops it — see plan §6 R2).
"""

import uuid  # noqa: TC003 — SQLAlchemy resolves `Mapped[uuid.UUID]` at runtime
from datetime import datetime  # noqa: TC003 — SQLAlchemy resolves `Mapped[datetime]` at runtime

from sqlalchemy import Enum as SAEnum
from sqlalchemy import ForeignKey, Index, String, Uuid, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from comradarr.db.base import Base, uuid_v7_pk_default
from comradarr.db.enums import CommandStatus


class PlannedCommand(Base):
    """A command queued for dispatch at a connector (Phase 9)."""

    __tablename__: str = "planned_commands"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        primary_key=True,
        default=uuid_v7_pk_default,
    )
    connector_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("connectors.id", ondelete="CASCADE"),
        nullable=False,
    )
    command_type: Mapped[str] = mapped_column(String, nullable=False)
    command_payload: Mapped[dict[str, object]] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
    )
    status: Mapped[CommandStatus] = mapped_column(
        SAEnum(CommandStatus, native_enum=True, name="command_status"),
        nullable=False,
        default=CommandStatus.PENDING,
    )
    # Populated by the dispatcher once the *arr side accepts the command.
    arr_command_id: Mapped[int | None] = mapped_column(nullable=True)
    dispatched_at: Mapped[datetime | None] = mapped_column(nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(nullable=True)
    created_at: Mapped[datetime] = mapped_column(nullable=False)

    __table_args__: tuple[Index, ...] = (  # noqa: RUF012  # SQLA convention
        Index(
            "ix_planned_commands_pending",
            "connector_id",
            "status",
            "created_at",
            postgresql_where=text("status = 'pending'"),
        ),
    )
