"""``search_schedule`` table — rotation state per content row (PRD §10).

The Phase 10 rotation engine reads this table to decide which content row to
search next: rows with the lowest ``tier`` and oldest ``last_searched_at`` win.
``paused = TRUE`` removes the row from rotation without losing its accumulated
counters — useful for the operator-facing "pause this series" affordance.

The composite PK ``(connector_id, content_type, content_arr_id)`` matches the
mirror tables' identity shape: ``connector_id`` scopes the row to its source,
``content_type`` discriminates series/episode/movie, and ``content_arr_id`` is
the *arr-side identifier (re-used because the mirror tables' PKs are the same
shape — there is no surrogate UUID to chase across joins).

Partial index — performance-critical for the rotation hot path:

    CREATE INDEX ix_search_schedule_active
        ON search_schedule (connector_id, tier, last_searched_at NULLS FIRST)
        WHERE NOT paused;

The ``postgresql_where`` argument is declared on the model so the intent is
co-located with the schema; Wave 2 hand-patches the autogenerated migration to
preserve the WHERE clause (autogenerate drops it — see plan §6 R2) and to add
the ``NULLS FIRST`` ordering on ``last_searched_at``.
"""

import uuid  # noqa: TC003 — SQLAlchemy resolves `Mapped[uuid.UUID]` at runtime
from datetime import datetime  # noqa: TC003 — SQLAlchemy resolves `Mapped[datetime]` at runtime

from sqlalchemy import Enum as SAEnum
from sqlalchemy import ForeignKey, Index, Uuid, text
from sqlalchemy.orm import Mapped, mapped_column

from comradarr.db.base import Base
from comradarr.db.enums import ContentType


class SearchSchedule(Base):
    """Rotation/search state per ``(connector, content)`` row (PRD §10)."""

    __tablename__: str = "search_schedule"

    connector_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("connectors.id", ondelete="CASCADE"),
        primary_key=True,
    )
    content_type: Mapped[ContentType] = mapped_column(
        SAEnum(ContentType, native_enum=True, name="content_type"),
        primary_key=True,
    )
    content_arr_id: Mapped[int] = mapped_column(primary_key=True)
    series_arr_id: Mapped[int | None] = mapped_column(nullable=True)
    season_number: Mapped[int | None] = mapped_column(nullable=True)
    tier: Mapped[int] = mapped_column(nullable=False)
    last_searched_at: Mapped[datetime | None] = mapped_column(nullable=True)
    search_count: Mapped[int] = mapped_column(default=0, nullable=False)
    paused: Mapped[bool] = mapped_column(default=False, nullable=False)

    __table_args__: tuple[Index, ...] = (  # noqa: RUF012  # SQLA convention
        Index(
            "ix_search_schedule_active",
            "connector_id",
            "tier",
            "last_searched_at",
            postgresql_where=text("NOT paused"),
        ),
    )
