"""v1 baseline schema.

Hand-patched per Phase 2 plan §5.2.3 + PRD §8: autogenerated from the
22-model declarative graph, then surgically edited for partial-index DDL
preservation, audit_log timestamp DESC ordering, search_schedule NULLS FIRST
ordering, and the three-role / GRANT matrix from PRD §8.

Revision ID: 361c239a829d
Revises:
Create Date: 2026-04-26 13:37:55.429874

The advisory-lock serialization for multi-worker startups is enforced by the
RUNNER (``comradarr.db.migrations.do_run_migrations``), not by this revision
file. The migration body is pure DDL + GRANTs; ``transactional_ddl=True``
is pinned on the runner side so the entire upgrade is one transaction.

RULE-MIGR-001 attestation: this file does NOT use ``op.batch_alter_table``.
RULE-LOG-001 attestation: this file emits NO log lines; failures raise a
structured ``RuntimeError`` that the runner logs through structlog.
"""

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.exc import ProgrammingError

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "361c239a829d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# GRANT matrix — driven from these two lists. The carve-out is enforced by
# membership: ``audit_log`` is in TABLES_FOR_AUDIT_GRANT only; every other
# application table is in TABLES_FOR_APP_GRANT only.
#
# GRANT-LIST EXTENSION CONTRACT (closes plan §6 F6):
#
#   When you add a new application table to the schema, you MUST also add
#   its name to one of these two lists in the SAME migration that creates
#   it. Forgetting yields a "permission denied for relation X" error at
#   runtime under the application role — silent at schema-creation time,
#   loud at first query. The Wave 4 role-permission test
#   (``test_role_permission_matrix``) asserts these lists agree with
#   ``Base.metadata.tables`` minus the audit-admin carve-out, so a missed
#   entry fails CI before it ships.
#
#   Audit carve-out rule: ``audit_log`` is the ONLY table that goes in
#   TABLES_FOR_AUDIT_GRANT; every other application table goes in
#   TABLES_FOR_APP_GRANT. Adding a new audit-style table requires a
#   targeted migration AND a plan amendment to PRD §8.
# ---------------------------------------------------------------------------

TABLES_FOR_APP_GRANT: tuple[str, ...] = (
    "app_config",
    "app_secrets",
    "auth_rate_limits",
    "role_permissions",
    "oidc_providers",
    "users",
    "sessions",
    "api_keys",
    "api_key_scopes",
    "user_preferences",
    "connectors",
    "mirror_series",
    "mirror_episodes",
    "mirror_movies",
    "search_schedule",
    "planned_commands",
    "priority_searches",
    "sync_state",
    "notification_channels",
    "notification_routes",
    "notification_templates",
)

TABLES_FOR_AUDIT_GRANT: tuple[str, ...] = ("audit_log",)


# Native PG ENUMs created by this migration. Listed once so ``downgrade()``
# can ``DROP TYPE`` each one without scattering string literals through the
# function body.
_PG_ENUM_TYPES: tuple[str, ...] = (
    "audit_action",
    "auth_provider",
    "channel_kind",
    "channel_test_status",
    "command_status",
    "connector_type",
    "content_type",
    "provisioning_provider",
    "sync_status",
    "user_role",
)


# ---------------------------------------------------------------------------
# upgrade() — thin try/except dispatcher; atomicity from transactional_ddl.
# ---------------------------------------------------------------------------


def upgrade() -> None:
    """Create the v1 baseline schema, roles, and GRANT matrix."""
    try:
        _create_tables_and_indexes()
    except ProgrammingError as exc:
        msg = (
            f"v1 baseline failed at _create_tables_and_indexes; "
            f"see docs/runbook/postgres-roles.md ({exc})"
        )
        raise RuntimeError(msg) from exc
    try:
        _create_roles_idempotent()
    except ProgrammingError as exc:
        msg = (
            f"v1 baseline failed at _create_roles_idempotent; "
            f"see docs/runbook/postgres-roles.md ({exc})"
        )
        raise RuntimeError(msg) from exc
    try:
        _apply_grants()
    except ProgrammingError as exc:
        msg = f"v1 baseline failed at _apply_grants; see docs/runbook/postgres-roles.md ({exc})"
        raise RuntimeError(msg) from exc


# ---------------------------------------------------------------------------
# Helper #1 — table + index DDL (autogenerated, then hand-patched).
# ---------------------------------------------------------------------------


def _create_tables_and_indexes() -> None:
    """Create all 22 application tables, indexes, and PG ENUM types.

    Hand-patches vs. raw autogenerate:

    * ``ix_audit_log_timestamp_desc`` and
      ``ix_audit_log_action_timestamp_desc`` use
      ``postgresql_ops={"timestamp": "DESC"}`` so the index ordering matches
      the read path documented in PRD §11. Autogenerate emits ascending.
    * ``ix_search_schedule_active`` uses ``postgresql_ops={"last_searched_at":
      "NULLS FIRST"}`` per PRD §10. Autogenerate omits the NULLS clause.
    * ``ix_planned_commands_pending`` carries the explicit
      ``postgresql_where=sa.text("status = 'pending'")``. Lowercase
      ``'pending'`` matches the StrEnum ``.value`` form bound to the ENUM
      via ``values_callable=lambda e: [m.value for m in e]`` on the model.
    """
    op.create_table(
        "app_config",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "app_secrets",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("value_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("value_tag", sa.LargeBinary(), nullable=True),
        sa.Column("value_key_version", sa.SmallInteger(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "auth_rate_limits",
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("counter", sa.Integer(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("backoff_delay", sa.Integer(), nullable=False),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("scope", "key"),
    )
    op.create_table(
        "connectors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("sonarr", "radarr", "prowlarr", name="connector_type"),
            nullable=False,
        ),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("api_key_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("api_key_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("api_key_tag", sa.LargeBinary(), nullable=True),
        sa.Column("api_key_key_version", sa.SmallInteger(), nullable=True),
        sa.Column(
            "per_connector_limits",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("insecure_skip_tls_verify", sa.Boolean(), nullable=False),
        sa.Column("tls_ca_bundle_path", sa.String(), nullable=True),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "oidc_providers",
        sa.Column("short_name", sa.String(), nullable=False),
        sa.Column("issuer_url", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("client_secret_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("client_secret_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("client_secret_tag", sa.LargeBinary(), nullable=True),
        sa.Column("client_secret_key_version", sa.SmallInteger(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("scope_list", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("discovery_url", sa.String(), nullable=False),
        sa.Column("discovery_cache", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("short_name"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_name", sa.String(), nullable=False),
        sa.Column("permission_name", sa.String(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("role_name", "permission_name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "operator", "viewer", name="user_role"),
            nullable=False,
        ),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column(
            "provisioning_provider",
            sa.Enum("local", "trusted_header", "oidc", name="provisioning_provider"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key_hash", sa.LargeBinary(), nullable=False),
        sa.Column("prefix", sa.String(), nullable=False),
        sa.Column("last_four", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "user.login.succeeded",
                "user.login.failed",
                "user.logout",
                "user.created",
                "user.updated",
                "user.deleted",
                "user.role_changed",
                "session.revoked",
                "api_key.issued",
                "api_key.revoked",
                "oidc_provider.created",
                "oidc_provider.updated",
                "oidc_provider.deleted",
                "connector.created",
                "connector.updated",
                "connector.deleted",
                "connector.paused",
                "connector.resumed",
                "notification_channel.created",
                "notification_channel.updated",
                "notification_channel.deleted",
                "notification_route.created",
                "notification_route.updated",
                "notification_route.deleted",
                "app_config.updated",
                "app_secret.updated",
                "setup.claimed",
                "search.priority_queued",
                "search.ran",
                name="audit_action",
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_ip", sa.String(), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=True),
        sa.Column("previous_hash", sa.LargeBinary(), nullable=True),
        sa.Column("content_hash", sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Hand-patched: DESC ordering on the timestamp column for both indexes.
    op.create_index(
        "ix_audit_log_action_timestamp_desc",
        "audit_log",
        ["action", "timestamp"],
        unique=False,
        postgresql_ops={"timestamp": "DESC"},
    )
    op.create_index(
        "ix_audit_log_timestamp_desc",
        "audit_log",
        ["timestamp"],
        unique=False,
        postgresql_ops={"timestamp": "DESC"},
    )
    op.create_table(
        "mirror_episodes",
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column("arr_id", sa.Integer(), nullable=False),
        sa.Column("series_arr_id", sa.Integer(), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column("has_file", sa.Boolean(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("connector_id", "arr_id"),
    )
    op.create_index(
        "ix_mirror_episodes_series_season",
        "mirror_episodes",
        ["connector_id", "series_arr_id", "season_number"],
        unique=False,
    )
    op.create_table(
        "mirror_movies",
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column("arr_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("monitored", sa.Boolean(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("connector_id", "arr_id"),
    )
    op.create_table(
        "mirror_series",
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column("arr_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("tvdb_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("monitored", sa.Boolean(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("connector_id", "arr_id"),
    )
    op.create_table(
        "notification_channels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("apprise", "webhook", "email", name="channel_kind"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("config_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("config_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("config_tag", sa.LargeBinary(), nullable=True),
        sa.Column("config_key_version", sa.SmallInteger(), nullable=True),
        sa.Column("insecure_skip_tls_verify", sa.Boolean(), nullable=False),
        sa.Column("tls_ca_bundle_path", sa.String(), nullable=True),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_test_status",
            sa.Enum("untested", "success", "failure", name="channel_test_status"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_channels_enabled_kind",
        "notification_channels",
        ["enabled", "kind"],
        unique=False,
    )
    op.create_index(
        "ix_notification_channels_user_id",
        "notification_channels",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "notification_templates",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column(
            "channel_kind",
            sa.Enum("apprise", "webhook", "email", name="channel_kind", create_type=False),
            nullable=False,
        ),
        sa.Column("subject_template", sa.String(), nullable=False),
        sa.Column("body_template", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "event_type", "channel_kind"),
    )
    op.create_table(
        "planned_commands",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column("command_type", sa.String(), nullable=False),
        sa.Column("command_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "dispatched",
                "resolved",
                "failed",
                name="command_status",
            ),
            nullable=False,
        ),
        sa.Column("arr_command_id", sa.Integer(), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Hand-patched: explicit postgresql_where carrying the lowercase enum
    # value form bound on the model via ``values_callable``.
    op.create_index(
        "ix_planned_commands_pending",
        "planned_commands",
        ["connector_id", "status", "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "priority_searches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column(
            "content_type",
            sa.Enum("series", "episode", "movie", name="content_type"),
            nullable=False,
        ),
        sa.Column("content_arr_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "connector_id",
            "content_type",
            "content_arr_id",
            name="uq_priority_searches_target",
        ),
    )
    op.create_table(
        "search_schedule",
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column(
            "content_type",
            sa.Enum("series", "episode", "movie", name="content_type", create_type=False),
            nullable=False,
        ),
        sa.Column("content_arr_id", sa.Integer(), nullable=False),
        sa.Column("series_arr_id", sa.Integer(), nullable=True),
        sa.Column("season_number", sa.Integer(), nullable=True),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("last_searched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("search_count", sa.Integer(), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("connector_id", "content_type", "content_arr_id"),
    )
    # Hand-patched: NULLS FIRST on last_searched_at (rotation hot path) +
    # explicit postgresql_where for the partial-index predicate.
    op.create_index(
        "ix_search_schedule_active",
        "search_schedule",
        ["connector_id", "tier", "last_searched_at"],
        unique=False,
        postgresql_where=sa.text("NOT paused"),
        postgresql_ops={"last_searched_at": "NULLS FIRST"},
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "auth_provider",
            sa.Enum("local", "trusted_header", "oidc", "api_key", name="auth_provider"),
            nullable=False,
        ),
        sa.Column("oidc_provider_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_token_hash"),
        "sessions",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "sync_state",
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column("last_full_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_deep_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_incremental_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fingerprint", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("idle", "running", "failed", name="sync_status"),
            nullable=False,
        ),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column("items_synced", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("connector_id"),
    )
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "key"),
    )
    op.create_table(
        "api_key_scopes",
        sa.Column("api_key_id", sa.Uuid(), nullable=False),
        sa.Column("permission_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["api_key_id"], ["api_keys.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("api_key_id", "permission_name"),
    )
    op.create_table(
        "notification_routes",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("predicate", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["notification_channels.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "event_type", "channel_id"),
    )
    op.create_index(
        "ix_notification_routes_user_event",
        "notification_routes",
        ["user_id", "event_type"],
        unique=False,
    )


# ---------------------------------------------------------------------------
# Helper #2 — idempotent role creation.
# ---------------------------------------------------------------------------


def _create_roles_idempotent() -> None:
    """Create the three Comradarr roles only if they don't already exist.

    Per PRD §8: ``comradarr_migration`` (DDL — used only at startup),
    ``comradarr_app`` (DML on every table EXCEPT audit_log carve-out),
    ``comradarr_audit_admin`` (SELECT/DELETE on audit_log only).

    NOLOGIN: roles are role-only, used as GRANT targets. Operators attach
    LOGIN credentials at provisioning time per the runbook
    (``docs/runbook/postgres-roles.md``).

    Idempotence: a single ``DO $$ ... IF NOT EXISTS ... CREATE ROLE`` block
    so a second ``upgrade head`` against an already-provisioned database is
    a no-op rather than a duplicate-role error.
    """
    op.execute(
        sa.text(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'comradarr_migration') THEN
                    CREATE ROLE comradarr_migration NOLOGIN;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'comradarr_app') THEN
                    CREATE ROLE comradarr_app NOLOGIN;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'comradarr_audit_admin') THEN
                    CREATE ROLE comradarr_audit_admin NOLOGIN;
                END IF;
            END
            $$;
            """,
        ),
    )


# ---------------------------------------------------------------------------
# Helper #3 — explicit per-table GRANT matrix.
# ---------------------------------------------------------------------------


def _apply_grants() -> None:
    """Apply the PRD §8 GRANT matrix; the audit carve-out is the security gate.

    See the module-level *GRANT-LIST EXTENSION CONTRACT* docblock (alongside
    :data:`TABLES_FOR_APP_GRANT` / :data:`TABLES_FOR_AUDIT_GRANT`) for the
    rule that governs adding new tables to the schema in later migrations
    (closes plan §6 F6).

    Migration role: ``ALL`` privileges on every table + every sequence +
    schema-level USAGE/CREATE so future migrations can run without manual
    GRANT replays.

    Application role: USAGE on schema, plus ``SELECT, INSERT, UPDATE,
    DELETE`` on every table in :data:`TABLES_FOR_APP_GRANT`. The
    ``audit_log`` table is NOT in that list; it gets ``SELECT, INSERT``
    only (no UPDATE, no DELETE) so an attacker who pivots through the
    application connection cannot rewrite or erase audit history.

    Audit-admin role: USAGE on schema, plus ``SELECT, DELETE`` on
    ``audit_log`` only. No INSERT (writes go through the application role's
    INSERT-only path); no UPDATE (audit rows are immutable once written);
    no privileges on any other table.
    """
    op.execute(sa.text("GRANT ALL ON ALL TABLES IN SCHEMA public TO comradarr_migration"))
    op.execute(sa.text("GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO comradarr_migration"))
    op.execute(sa.text("GRANT USAGE, CREATE ON SCHEMA public TO comradarr_migration"))

    op.execute(sa.text("GRANT USAGE ON SCHEMA public TO comradarr_app"))
    for tablename in TABLES_FOR_APP_GRANT:
        op.execute(
            sa.text(f'GRANT SELECT, INSERT, UPDATE, DELETE ON "{tablename}" TO comradarr_app'),
        )
    # audit_log carve-out — INSERT + SELECT only for the application role.
    op.execute(sa.text("GRANT SELECT, INSERT ON audit_log TO comradarr_app"))

    op.execute(sa.text("GRANT USAGE ON SCHEMA public TO comradarr_audit_admin"))
    for tablename in TABLES_FOR_AUDIT_GRANT:
        op.execute(sa.text(f'GRANT SELECT, DELETE ON "{tablename}" TO comradarr_audit_admin'))


# ---------------------------------------------------------------------------
# downgrade() — reverse FK order; DROP TYPE every PG ENUM; DO NOT DROP ROLE.
# ---------------------------------------------------------------------------


def downgrade() -> None:
    """Drop the v1 baseline schema and PG ENUMs; leave roles intact.

    Roles are intentionally left in place: they may be referenced by
    operator-managed grants outside this schema (cross-schema audit
    forwarders, external secrets vault hooks). The runbook documents the
    explicit ``DROP ROLE`` path operators run after a tear-down.

    Drop order is FK-respecting: tables with inbound FKs are dropped after
    the dependents that reference them.
    """
    op.drop_index("ix_notification_routes_user_event", table_name="notification_routes")
    op.drop_table("notification_routes")
    op.drop_table("api_key_scopes")
    op.drop_table("user_preferences")
    op.drop_table("sync_state")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(
        "ix_search_schedule_active",
        table_name="search_schedule",
        postgresql_where=sa.text("NOT paused"),
    )
    op.drop_table("search_schedule")
    op.drop_table("priority_searches")
    op.drop_index(
        "ix_planned_commands_pending",
        table_name="planned_commands",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("planned_commands")
    op.drop_table("notification_templates")
    op.drop_index("ix_notification_channels_user_id", table_name="notification_channels")
    op.drop_index("ix_notification_channels_enabled_kind", table_name="notification_channels")
    op.drop_table("notification_channels")
    op.drop_table("mirror_series")
    op.drop_table("mirror_movies")
    op.drop_index("ix_mirror_episodes_series_season", table_name="mirror_episodes")
    op.drop_table("mirror_episodes")
    op.drop_index("ix_audit_log_timestamp_desc", table_name="audit_log")
    op.drop_index("ix_audit_log_action_timestamp_desc", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("role_permissions")
    op.drop_table("oidc_providers")
    op.drop_table("connectors")
    op.drop_table("auth_rate_limits")
    op.drop_table("app_secrets")
    op.drop_table("app_config")

    # Drop PG ENUM types — autogenerate omits these; leaving them behind
    # would block a re-upgrade against the same database.
    for enum_name in _PG_ENUM_TYPES:
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
